export const ADD_TODO = "ADD_TODO";
export const EDIT_TODO = "EDIT_TODO";
export const DELETE_TODO = "DELETE_TODO";
export const TOGGLE_TODO_VIEW = "TOGGLE_TODO";
export const TOGGLE_TODO_STATE = "TOGGLE_TODO_STATE";

export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
export const TOGGLE_TODO_PROMPT = "TOGGLE_TODO_PROMPT";
export const DESERIALIZE_TODOS = "DESERIALIZE_TODOS";
